
dist: trusty
sudo: required

language: node_js
node_js:
  - '10'

matrix:
  include:
    - os: linux
      before_install: # 为了支持打包rpm格式的包
          - sudo apt-get update
          # - sudo apt-get install snapd -y
          # - sudo snap install snapcraft --classic
          # - sudo snap refresh
          # - sudo snap install snapcraft --classic
          # - sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib
          # - sudo apt-get install --no-install-recommends -y rpm
    - os: osx

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g electron-installer-snap

script:
  - npm run lint
  - npm run release

branches:
  only:
    - master