
dist: trusty
sudo: required

language: node_js
node_js:
  - '10'

matrix:
  include:
    - os: linux
    - os: osx

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run packapp
  - npm run release

branches:
  only:
    - master