version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2019
platform: Any CPU
environment:
  GH_TOKEN:
    secure: p3N9nAtWTIEuQlVJNnyoh9iGi/tIcl1dsUbdk3kLUfblKVT5wZvnNa4o0uyuXWjV
cache:
  - node_modules

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - git reset --hard HEAD
  - yarn
  - node --version

build_script:
  - yarn build
  - yarn packapp

test: off
